engines:
 eslint:
   enabled: true
 pep8:
   enabled: true
ratings:
 paths:
 - "**.js"
 - "**.py"
exclude_paths:
- test/resources/**
- web/lib/**
- js/lib/beautify.js
- js/lib/beautify-css.js
- js/lib/beautify-html.js
- tools/template/*
- "**/generated/*"
